apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.mogyuchi.jp
  statusbadge.enabled: "true"
  admin.enabled: "false"
  users.anonymous.enabled: "true"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Iv23liihKd6wDsQNqJDY
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: mogyugyu
  exec.enabled: "true"
