apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-art-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
  destination:
    namespace: art-runners
    server: https://kubernetes.default.svc
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.12.1
    helm:
      releaseName: arc-runner-set
      parameters:
        - name: githubConfigUrl
          value: "https://github.com/Misskey-art"
        - name: githubConfigSecret
          value: "pre-defined-secret"
        - name: controllerServiceAccount.namespace
          value: arc-systems
        - name: controllerServiceAccount.name
          value: arc-gha-rs-controller
      values: |
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                command: ["/home/runner/run.sh"]
                resources:
                  limits:
                    cpu: 1000m
                    memory: 3000Mi
  project: gha-runner
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
      - PruneLast=true
