apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
  name: gha-eoeo-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eoeo-runners
    server: https://kubernetes.default.svc
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.10.1
    helm:
      parameters:
        - name: runnerScaleSetName
          value: "eoeo-x64"
        - name: githubConfigUrl
          value: "https://github.com/eoeo-org"
        - name: githubConfigSecret
          value: "pre-defined-secret"
        - name: controllerServiceAccount.namespace
          value: arc-systems
        - name: controllerServiceAccount.name
          value: arc-gha-rs-controller
      values: |
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest@sha256:831a2607a2618e4b79d9323b4c72330f3861768a061c2b92a845e9d214d80e5b
                command: ["/home/runner/run.sh"]
                resources:
                  limits:
                    cpu: 1000m
                    memory: 3000Mi
  project: gha-runner
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
      - PruneLast=true
