apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.14.4
  - ingress.yaml

patches:
  - path: https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.4/notifications_catalog/install.yaml
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-cmd-params-cm.yaml
  - path: overlays/argocd-notifications-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
