apiVersion: apps/v1
kind: Deployment
metadata:
  name: smee
  labels:
    app.kubernetes.io/name: smee
    app: smee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smee
  template:
    metadata:
      labels:
        app: smee
    spec:
      containers:
        - name: smee
          image: ghcr.io/probot/smee.io:latest@sha256:da59f1cac4b8f39ef2b21873dbf6d0c8573994c36132b9009489647d997e49cf
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent # because digest pinning
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
