apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                      - oracle
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:26515e5f5e92a4ad0a0cde24f873adf80847734c0ab3dbcd642b55ba62d34be1
          imagePullPolicy: IfNotPresent # because digest pinning
          envFrom:
            - secretRef:
                name: buchubot-token
          volumeMounts:
            - name: config-volume
              mountPath: /app
              subPath: config-dir
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: config-volume
          configMap:
            name: buchubot-config
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
