apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                      - oracle
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:2bade783bc83c76ac6719454e691bab9a92a612d2e7fa92b9806e9b64cd17326
          imagePullPolicy: IfNotPresent # because digest pinning
          envFrom:
            - secretRef:
                name: buchubot-token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
