apiVersion: apps/v1
kind: Deployment
metadata:
  name: buchubot
  labels:
    app: buchubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buchubot
  template:
    metadata:
      labels:
        app: buchubot
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                      - oracle
      containers:
        - name: buchubot
          image: ghcr.io/kazukazu123123/buchubot:main@sha256:02d46aaf5ae5c6a459522f14c0f7db048752839166800c20edeb0d364700028a
          imagePullPolicy: IfNotPresent # because digest pinning
          envFrom:
            - secretRef:
                name: buchubot-token
          env:
            - name: BUCHUBOT_CONFIG_PATH
              value: /config/config.toml
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: config-volume
          configMap:
            name: buchubot-config
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
