apiVersion: apps/v1
kind: Deployment
metadata:
  name: pow-summon-bot
  labels:
    app: pow-summon-bot
  annotations:
    link.argocd.argoproj.io/external-link: https://discord.com/oauth2/authorize?client_id=1105143574066122933
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pow-summon-bot
  template:
    metadata:
      labels:
        app: pow-summon-bot
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                      - oracle
      containers:
        - name: pow-summon-bot
          image: ghcr.io/eoeo-org/pow-summon-discordbot:1.1.30@sha256:d88696e436ac81dd8219d154ba549aa1e65cf66c2265f4dfafd6c133e50164e6
          imagePullPolicy: IfNotPresent # because digest pinning
          envFrom:
            - secretRef:
                name: pow-summon-bot-token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      tolerations:
        - key: "low-spec"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
